### ISSUE TITLE
Example for types with parameters

### ISSUE THREAD

**Issue by vigna** [kas-gui/impl-tools#44]
I need to autoimpl `&T`, `&mut T` on a type with parameters. The only hint I found in the docs is:

Note further: if the trait uses generic parameters itself, these must be introduced explicitly in the for<..> parameter list.

I couldn't find an example, and I tried really hard to transalte this "must be introduced explicitly", to no avail. A three-line example would be amazing...

**Comment by dhardy** [comment]
You mean like this?
```rust
#[autoimpl(for<'a, T> &'a T, &'a mut T, Box<T> where T: trait + ?Sized)]
trait G<V>
where
    V: Debug,
{
    fn g(&self) -> V;

    fn s<X>(&self, f: impl Fn(V) -> X) -> X
    where
        Self: Sized,
    {
        f(self.g())
    }
}
```
(from the `tests` sub-dir)

**Comment by vigna** [comment]
Yes, but in the docs. Thanks for the pointer.

Tho, I cannot understand the phrase from the docs "if the trait uses generic parameters itself, these must be introduced explicitly in the for<..> parameter list", because V does not appear in the list, as the docs suggests.

**Comment by vigna** [comment]
Ok, I realized I was relying on the analyzer. The problem is not in the parameter—the problem is that this won't compile:
```
#[autoimpl(for<'a, T> &'a mut T where T: trait + ?Sized)]
pub trait BitRead2 {
    fn copy_to(&mut self, mut n: u64) -> Result<(), std::convert::Infallible> {
        Ok(())
    }
}
```
I get
```
error: expected expression, found keyword `mut`
   --> src/traits/bits.rs:135:27
    |
135 |     fn copy_to(&mut self, mut n: u64) -> Result<(), std::convert::Infallible> {
    |                           ^^^ expected expression
```
I compiles without problems if I remove the autoimpl.

**Comment by dhardy** [comment]
Looks like my macro can't parse `mut` in this position. Thanks for the bug report.

**Comment by vigna** [comment]
I would also fix the phrase above—as it stands, from the example you provided me, it provides false information.

**Comment by dhardy** [comment]
The doc line mentioned (`src/lib.rs:283`) appears to be erroneous, yes. (Most likely outdated docs. Macros are hard to document; at least I've yet to find a good approach.)

I need to re-read the docs, but it looks like this paragraph should just be deleted. Anyway, I'll leave the doc fixes for a new PR.
