### ISSUE TITLE
Support #[autoimpl] on enums?

### ISSUE THREAD

**Issue by dhardy** [kas-gui/impl-tools#6]
Currently `#[autoimpl]` supports three modes of operation:

1. On structs, impl traits targetting many fields (e.g. `Clone`, `Debug`)
2. On structs, impl traits targetting one field (e.g. `Deref`)
3. On traits, impl for certain types supporting `Deref` to another type which supports the trait

Each has special syntax: (1) supports `ignore self.a, self.b`; (2) supports `using self.foo`; (3) supports `for<'a, T>`.

Now, `derive(Clone)` etc. supports enums. This has nothing to do with `derive` and everything to do with the impl for `Clone`, which uses a low level interface. `#[autoimpl]` uses a much higher-level interface, such that we parse the target struct/trait and confirm fields mentioned by `ignore` / `using` exist before even touching code specific to `Clone`, `Deref` etc.

So, the question is, *if* we let `#[autoimpl]` support enums, then what syntax should be supported and what restrictions should we have?

E.g. should we support ignoring like this?
```rust
#[autoimpl(Debug ignore self.1)]
enum X {
    A(i32, ()),
    B(f32, ()),
}
```
If so, should we require that each enum variant has a tuple form such that `self.1` is valid?

Should we support this, where fields mentioned by `ignore` may not apply to all variants?
```rust
#[autoimpl(Debug ignore self.x, self.y)]
enum E {
    A,
    B(i32),
    C { a: i8, x: () }
    D { a: u8, y: () }
}
```

Should we allow this?
```rust
#[autoimpl(Deref using self.foo)]
enum Y {
    A { foo: Foo },
    B { foo: Foo, x: f32 },
}
```

And thus this (custom `Target` syntax is supported by #26):
```rust
#[autoimpl(Deref<Target = Foo> using self.foo)]
enum Y {
    A { foo: A }, // require: A: Foo
    B { foo: B, x: f32 }, // require: B: Foo
}
```

**Comment by dhardy** [comment]
We should probably at least support simple cases:
```rust

#[autoimpl(Debug where T: trait)]
enum Option<T> {
    None,
    Some(T),
}
```

**Comment by ycscaly** [comment]
Are there plans to support this? I definitely need this feature

**Comment by dhardy** [comment]
Please detail exactly what you'd like to see supported.

**Comment by ycscaly** [comment]
Most importantly deriving Debug and Clone, and the ability to ignore fields e.g.:
`#[autoimpl(Debug ignore self.x, self.y)]
`

The motivation behind it is that I have enums that are generic over some parameter which isn't debuggable, but the enum itself doesn't use that parameter but a structure that takes it as parameter itself and [derive doesn't work in that case](https://github.com/rust-lang/rust/issues/26925). e.g.
`pub(super) enum Message<E: Curve, Sig: Clone + Debug, Kem: hpke::kem::Kem, H: Digest + Clone> {
    Message1(Message1<Sig>),
    Message2(Message2<E, Sig, H>),
    Message3(Message3<E, Sig, Kem>),
}`

**Comment by ycscaly** [comment]
Exactly. Thank you.
